name: deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ github.ref_name == 'main' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ github.ref_name == 'main' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      AWS_DEFAULT_REGION: 'us-west-2'
      STAGE_SUFFIX: ${{ github.ref_name == 'main' && '-prod' || '-dev' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: print name
        run: echo $STAGE_SUFFIX
      - name: Get and Set bucket name
        run: |
          suffix=$STAGE_SUFFIX
          cmd="$(aws ssm get-parameter --name "/deploy/bucket/$($suffix)" --output json --region us-west-2 | jq '.Parameter.Value')"
          echo "BUCKET_NAME=$cmd" >> "$GITHUB_ENV"
      - name: Get and Set bucket name
        run: |
          suffix=$STAGE_SUFFIX
          cmd="$(aws ssm get-parameter --name "/deploy/distribution/$suffix" --output json --region us-west-2 | jq '.Parameter.Value')"
          echo "DISTRIBUTION=$cmd" >> "$GITHUB_ENV"
      - name: Update to s3
        run: aws s3 cp ./dist/ s3://${{ env.BUCKET_NAME }} --recursive
      - name: remove cache of cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION }} --paths "/*"